apiVersion: v1
kind: Pod
metadata:
  name: debian-pod
spec:
  containers:
  - name: debian-container
    image: dherrero/midebian

    imagePullPolicy: IfNotPresent 
    args:
    - sleep
    - infinity
